package com.google.android.gms.internal.ads;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import defpackage.Th;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.annotation.ParametersAreNonnullByDefault;

/* JADX INFO: loaded from: classes3.dex */
@ParametersAreNonnullByDefault
public final class zzcam extends defpackage.com5Fixed {
    public static final Parcelable.Creator<zzcam> CREATOR = new zzcan();
    public final long zzA;
    public final String zzB;
    public final float zzC;
    public final int zzD;
    public final int zzE;
    public final boolean zzF;
    public final String zzG;
    public final boolean zzH;
    public final String zzI;
    public final boolean zzJ;
    public final int zzK;
    public final Bundle zzL;
    public final String zzM;
    public final com.google.android.gms.ads.internal.client.zzdo zzN;
    public final boolean zzO;
    public final Bundle zzP;
    public final String zzQ;
    public final String zzR;
    public final String zzS;
    public final boolean zzT;
    public final List zzU;
    public final String zzV;
    public final List zzW;
    public final int zzX;
    public final boolean zzY;
    public final boolean zzZ;
    public final int zza;
    public final boolean zzaa;
    public final ArrayList zzab;
    public final String zzac;
    public final zzbrx zzad;
    public final String zzae;
    public final Bundle zzaf;
    public final Bundle zzb;
    public final com.google.android.gms.ads.internal.client.zzl zzc;
    public final com.google.android.gms.ads.internal.client.zzq zzd;
    public final String zze;
    public final ApplicationInfo zzf;
    public final PackageInfo zzg;
    public final String zzh;
    public final String zzi;
    public final String zzj;
    public final zzcgt zzk;
    public final Bundle zzl;
    public final int zzm;
    public final List zzn;
    public final Bundle zzo;
    public final boolean zzp;
    public final int zzq;
    public final int zzr;
    public final float zzs;
    public final String zzt;
    public final long zzu;
    public final String zzv;
    public final List zzw;
    public final String zzx;
    public final zzblo zzy;
    public final List zzz;

    public zzcam(int i, Bundle bundle, com.google.android.gms.ads.internal.client.zzl zzlVar, com.google.android.gms.ads.internal.client.zzq zzqVar, String str, ApplicationInfo applicationInfo, PackageInfo packageInfo, String str2, String str3, String str4, zzcgt zzcgtVar, Bundle bundle2, int i2, ArrayList arrayList, Bundle bundle3, boolean z, int i3, int i4, float f, String str5, long j, String str6, ArrayList arrayList2, String str7, zzblo zzbloVar, ArrayList arrayList3, long j2, String str8, float f2, boolean z2, int i5, int i6, boolean z3, String str9, String str10, boolean z4, int i7, Bundle bundle4, String str11, com.google.android.gms.ads.internal.client.zzdo zzdoVar, boolean z5, Bundle bundle5, String str12, String str13, String str14, boolean z6, ArrayList arrayList4, String str15, ArrayList arrayList5, int i8, boolean z7, boolean z8, boolean z9, ArrayList arrayList6, String str16, zzbrx zzbrxVar, String str17, Bundle bundle6) {
        this.zza = i;
        this.zzb = bundle;
        this.zzc = zzlVar;
        this.zzd = zzqVar;
        this.zze = str;
        this.zzf = applicationInfo;
        this.zzg = packageInfo;
        this.zzh = str2;
        this.zzi = str3;
        this.zzj = str4;
        this.zzk = zzcgtVar;
        this.zzl = bundle2;
        this.zzm = i2;
        this.zzn = arrayList;
        this.zzz = arrayList3 == null ? Collections.emptyList() : Collections.unmodifiableList(arrayList3);
        this.zzo = bundle3;
        this.zzp = z;
        this.zzq = i3;
        this.zzr = i4;
        this.zzs = f;
        this.zzt = str5;
        this.zzu = j;
        this.zzv = str6;
        this.zzw = arrayList2 == null ? Collections.emptyList() : Collections.unmodifiableList(arrayList2);
        this.zzx = str7;
        this.zzy = zzbloVar;
        this.zzA = j2;
        this.zzB = str8;
        this.zzC = f2;
        this.zzH = z2;
        this.zzD = i5;
        this.zzE = i6;
        this.zzF = z3;
        this.zzG = str9;
        this.zzI = str10;
        this.zzJ = z4;
        this.zzK = i7;
        this.zzL = bundle4;
        this.zzM = str11;
        this.zzN = zzdoVar;
        this.zzO = z5;
        this.zzP = bundle5;
        this.zzQ = str12;
        this.zzR = str13;
        this.zzS = str14;
        this.zzT = z6;
        this.zzU = arrayList4;
        this.zzV = str15;
        this.zzW = arrayList5;
        this.zzX = i8;
        this.zzY = z7;
        this.zzZ = z8;
        this.zzaa = z9;
        this.zzab = arrayList6;
        this.zzac = str16;
        this.zzad = zzbrxVar;
        this.zzae = str17;
        this.zzaf = bundle6;
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i) {
        int iP = Th.P(parcel, 20293);
        Th.G(parcel, 1, this.zza);
        Th.A(parcel, 2, this.zzb);
        Th.I(parcel, 3, this.zzc, i);
        Th.I(parcel, 4, this.zzd, i);
        Th.J(parcel, 5, this.zze);
        Th.I(parcel, 6, this.zzf, i);
        Th.I(parcel, 7, this.zzg, i);
        Th.J(parcel, 8, this.zzh);
        Th.J(parcel, 9, this.zzi);
        Th.J(parcel, 10, this.zzj);
        Th.I(parcel, 11, this.zzk, i);
        Th.A(parcel, 12, this.zzl);
        Th.G(parcel, 13, this.zzm);
        Th.L(parcel, 14, this.zzn);
        Th.A(parcel, 15, this.zzo);
        Th.z(parcel, 16, this.zzp);
        Th.G(parcel, 18, this.zzq);
        Th.G(parcel, 19, this.zzr);
        float f = this.zzs;
        parcel.writeInt(262164);
        parcel.writeFloat(f);
        Th.J(parcel, 21, this.zzt);
        Th.H(parcel, 25, this.zzu);
        Th.J(parcel, 26, this.zzv);
        Th.L(parcel, 27, this.zzw);
        Th.J(parcel, 28, this.zzx);
        Th.I(parcel, 29, this.zzy, i);
        Th.L(parcel, 30, this.zzz);
        Th.H(parcel, 31, this.zzA);
        Th.J(parcel, 33, this.zzB);
        float f2 = this.zzC;
        parcel.writeInt(262178);
        parcel.writeFloat(f2);
        Th.G(parcel, 35, this.zzD);
        Th.G(parcel, 36, this.zzE);
        Th.z(parcel, 37, this.zzF);
        Th.J(parcel, 39, this.zzG);
        Th.z(parcel, 40, this.zzH);
        Th.J(parcel, 41, this.zzI);
        Th.z(parcel, 42, this.zzJ);
        Th.G(parcel, 43, this.zzK);
        Th.A(parcel, 44, this.zzL);
        Th.J(parcel, 45, this.zzM);
        Th.I(parcel, 46, this.zzN, i);
        Th.z(parcel, 47, this.zzO);
        Th.A(parcel, 48, this.zzP);
        Th.J(parcel, 49, this.zzQ);
        Th.J(parcel, 50, this.zzR);
        Th.J(parcel, 51, this.zzS);
        Th.z(parcel, 52, this.zzT);
        List list = this.zzU;
        if (list != null) {
            int iP2 = Th.P(parcel, 53);
            int size = list.size();
            parcel.writeInt(size);
            for (int i2 = 0; i2 < size; i2++) {
                parcel.writeInt(((Integer) list.get(i2)).intValue());
            }
            Th.X(parcel, iP2);
        }
        Th.J(parcel, 54, this.zzV);
        Th.L(parcel, 55, this.zzW);
        Th.G(parcel, 56, this.zzX);
        Th.z(parcel, 57, this.zzY);
        Th.z(parcel, 58, this.zzZ);
        Th.z(parcel, 59, this.zzaa);
        Th.L(parcel, 60, this.zzab);
        Th.J(parcel, 61, this.zzac);
        Th.I(parcel, 63, this.zzad, i);
        Th.J(parcel, 64, this.zzae);
        Th.A(parcel, 65, this.zzaf);
        Th.X(parcel, iP);
    }
}
