package com.revenuecat.purchases.parceler;

import android.os.Parcel;
import defpackage.lp2;
import org.json.JSONObject;

/* JADX INFO: loaded from: classes3.dex */
public final class JSONObjectParceler {
    public static final JSONObjectParceler INSTANCE = new JSONObjectParceler();

    private JSONObjectParceler() {
    }

    public JSONObject create(Parcel parcel) {
        return new JSONObject(parcel.readString());
    }

    public JSONObject[] newArray(int i) {
        throw new lp2("Generated by Android Extensions automatically");
    }

    public void write(JSONObject jSONObject, Parcel parcel, int i) {
        parcel.writeString(jSONObject.toString());
    }
}
