package com.android.billingclient.api;

/* JADX INFO: loaded from: classes.dex */
public final class T23 {
    public static final NUlFixed a;
    public static final NUlFixed b;
    public static final NUlFixed c;
    public static final NUlFixed d;
    public static final NUlFixed e;
    public static final NUlFixed f;
    public static final NUlFixed g;
    public static final NUlFixed h;
    public static final NUlFixed i;
    public static final NUlFixed j;
    public static final NUlFixed k;
    public static final NUlFixed l;
    public static final NUlFixed m;
    public static final NUlFixed n;
    public static final NUlFixed o;
    public static final NUlFixed p;
    public static final NUlFixed q;
    public static final NUlFixed r;
    public static final NUlFixed s;
    public static final NUlFixed t;
    public static final NUlFixed u;
    public static final NUlFixed v;
    public static final NUlFixed w;
    public static final NUlFixed x;
    public static final NUlFixed y;

    static {
        NUlFixed.QnHx qnHxA = NUlFixed.a();
        qnHxA.a = 3;
        qnHxA.b = "Google Play In-app Billing API version is less than 3";
        a = qnHxA.a();
        NUlFixed.QnHx qnHxA2 = NUlFixed.a();
        qnHxA2.a = 3;
        qnHxA2.b = "Google Play In-app Billing API version is less than 9";
        b = qnHxA2.a();
        NUlFixed.QnHx qnHxA3 = NUlFixed.a();
        qnHxA3.a = 3;
        qnHxA3.b = "Billing service unavailable on device.";
        c = qnHxA3.a();
        NUlFixed.QnHx qnHxA4 = NUlFixed.a();
        qnHxA4.a = 5;
        qnHxA4.b = "Client is already in the process of connecting to billing service.";
        d = qnHxA4.a();
        NUlFixed.QnHx qnHxA5 = NUlFixed.a();
        qnHxA5.a = 5;
        qnHxA5.b = "The list of SKUs can't be empty.";
        e = qnHxA5.a();
        NUlFixed.QnHx qnHxA6 = NUlFixed.a();
        qnHxA6.a = 5;
        qnHxA6.b = "SKU type can't be empty.";
        f = qnHxA6.a();
        NUlFixed.QnHx qnHxA7 = NUlFixed.a();
        qnHxA7.a = 5;
        qnHxA7.b = "Product type can't be empty.";
        g = qnHxA7.a();
        NUlFixed.QnHx qnHxA8 = NUlFixed.a();
        qnHxA8.a = -2;
        qnHxA8.b = "Client does not support extra params.";
        h = qnHxA8.a();
        NUlFixed.QnHx qnHxA9 = NUlFixed.a();
        qnHxA9.a = 5;
        qnHxA9.b = "Invalid purchase token.";
        i = qnHxA9.a();
        NUlFixed.QnHx qnHxA10 = NUlFixed.a();
        qnHxA10.a = 6;
        qnHxA10.b = "An internal error occurred.";
        j = qnHxA10.a();
        NUlFixed.QnHx qnHxA11 = NUlFixed.a();
        qnHxA11.a = 5;
        qnHxA11.b = "SKU can't be null.";
        qnHxA11.a();
        NUlFixed.QnHx qnHxA12 = NUlFixed.a();
        qnHxA12.a = 0;
        k = qnHxA12.a();
        NUlFixed.QnHx qnHxA13 = NUlFixed.a();
        qnHxA13.a = -1;
        qnHxA13.b = "Service connection is disconnected.";
        l = qnHxA13.a();
        NUlFixed.QnHx qnHxA14 = NUlFixed.a();
        qnHxA14.a = -3;
        qnHxA14.b = "Timeout communicating with service.";
        m = qnHxA14.a();
        NUlFixed.QnHx qnHxA15 = NUlFixed.a();
        qnHxA15.a = -2;
        qnHxA15.b = "Client does not support subscriptions.";
        n = qnHxA15.a();
        NUlFixed.QnHx qnHxA16 = NUlFixed.a();
        qnHxA16.a = -2;
        qnHxA16.b = "Client does not support subscriptions update.";
        o = qnHxA16.a();
        NUlFixed.QnHx qnHxA17 = NUlFixed.a();
        qnHxA17.a = -2;
        qnHxA17.b = "Client does not support get purchase history.";
        p = qnHxA17.a();
        NUlFixed.QnHx qnHxA18 = NUlFixed.a();
        qnHxA18.a = -2;
        qnHxA18.b = "Client does not support price change confirmation.";
        q = qnHxA18.a();
        NUlFixed.QnHx qnHxA19 = NUlFixed.a();
        qnHxA19.a = -2;
        qnHxA19.b = "Client does not support billing on VR.";
        r = qnHxA19.a();
        NUlFixed.QnHx qnHxA20 = NUlFixed.a();
        qnHxA20.a = -2;
        qnHxA20.b = "Play Store version installed does not support cross selling products.";
        s = qnHxA20.a();
        NUlFixed.QnHx qnHxA21 = NUlFixed.a();
        qnHxA21.a = -2;
        qnHxA21.b = "Client does not support multi-item purchases.";
        t = qnHxA21.a();
        NUlFixed.QnHx qnHxA22 = NUlFixed.a();
        qnHxA22.a = -2;
        qnHxA22.b = "Client does not support offer_id_token.";
        u = qnHxA22.a();
        NUlFixed.QnHx qnHxA23 = NUlFixed.a();
        qnHxA23.a = -2;
        qnHxA23.b = "Client does not support ProductDetails.";
        v = qnHxA23.a();
        NUlFixed.QnHx qnHxA24 = NUlFixed.a();
        qnHxA24.a = -2;
        qnHxA24.b = "Client does not support in-app messages.";
        w = qnHxA24.a();
        NUlFixed.QnHx qnHxA25 = NUlFixed.a();
        qnHxA25.a = -2;
        qnHxA25.b = "Client does not support alternative billing.";
        x = qnHxA25.a();
        NUlFixed.QnHx qnHxA26 = NUlFixed.a();
        qnHxA26.a = 5;
        qnHxA26.b = "Unknown feature";
        y = qnHxA26.a();
    }
}
